#!/bin/bash

count=1
g++ Source/main.cpp

for((; count<16; count++))
do
    input="Test/test$count.txt"
    if [ -f $input ]
    then
        echo "[LOG] Input file found";
    else
        echo "No such input file which named \"$input\"! Aborting!";
	exit 1
    fi
    echo "[Test#$count]: "
    ./a.out < $input
    echo ______________________________
done
echo "All values calculated"
