#!/bin/bash

IFS=$'\n'
echo "Enter input file path" 
read input
echo "Enter result file path"
read results
if [ -f $input ]
then
    echo "[Input file founded]";
else
    echo "[ERROR] No such input file which named \"$input\"! Aborting!";
    exit 1
fi
g++ main.cpp

echo __________________________________
count=1
for value in $(cat $results)
do
    result_arr[$count]=$value
    let count=$count+1
done

curr_count=1
for value in $(cat $input)
do
    if [ $curr_count -eq $count ]; then
	echo "[ERROR] Invalid args number in input file";
	echo "Shutting down"
	exit 1;
    fi
    echo -n "Test#$curr_count: "
    curr=$(./a.out <<< $value)
    answer=${result_arr[$curr_count]}
    echo -n "$curr  "
    if [ $curr -eq $answer ]
    then
	echo [correctly]
    else
	echo "[incorrectly (answer = $answer)]"
    fi
    let curr_count=$curr_count+1
done
echo "Shutting down"
